config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'static_pages#index'
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, param: :category_name, only: [:index, :show] do
    get ':id', to: 'pictures#show', as: 'picture'
  end
  resources :pictures, only: [:index]
  resources :comments, only: [:index]
  post '/:picture_id/comments', to: 'comments#create', as: 'create_comment'
  resources :likes, path: '/:picture_id/likes', only: [:create, :destroy]
  resources :events, only: [:index]
  resources :subscriptions, path: '/:category_id/subscriptions', only: [:create, :destroy]

  resources :chat_rooms, only: [:new, :create, :index, :show]

  get 'events/:id/comments', to: 'events#user_comments', as: 'user_comments'
  get 'events/:id/likes', to: 'events#user_likes', as: 'user_likes'
  get 'events/:id/navigation', to: 'events#user_navigation', as: 'user_navigation'
  get 'events/:id/user_sign_in', to: 'events#user_sign_in', as: 'user_sign_in'
  get 'events/:id/user_sign_out', to: 'events#user_sign_out', as: 'user_sign_out'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server.new, :at => '/resque'
  mount ActionCable.server, :at => '/cable'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :url, presence: true
  validates :user, presence: true
  validates :confirmation, inclusion: { in: [true, false] },
                           exclusion: { in: [nil] }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user, only: [:user_navigation, :user_likes, :user_comments, :user_sign_in, :user_sign_out]

  def index
    @users = User.all.page(params[:page]).per(20)
  end

  def user_navigation
    @navigations = @user.events.page(params[:page]).per(20)
  end

  def user_sign_in
    @actions = @user.events.where(url: '/users/sign_in', confirmation: true).page(params[:page]).per(20)
  end

  def user_sign_out
    @actions = @user.events.where(url: '/users/sign_out', confirmation: true).page(params[:page]).per(20)
  end

  def user_likes
    @likes = @user.likes.page(params[:page]).per(20)
  end

  def user_comments
    @comments = @user.comments.page(params[:page]).per(20)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/events/index.html.haml
.page-header
  %h1.text-center= t('.events')
%table.table
  %thead
    %th= t('.user')
    %th{colspan: '5'}= t('.actions')
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= link_to t('.navigation'), user_navigation_path(user.id)
        %td= link_to t('.sign_in'), user_sign_in_path(user.id)
        %td= link_to t('.sign_out'), user_sign_out_path(user.id)
        %td= link_to t('.likes'), user_likes_path(user.id)
        %td= link_to t('.comments'), user_comments_path(user.id)
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @users

app/views/events/user_comments.html.haml
.page-header
  %h1.text-center
    = @user.email
    = t('.comments')
%table.table
  %thead
    %th= t('.date_time')
    %th= t('.picture')
    %th= t('.comment')
  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.created_at
        %td= comment.picture_id
        %td= comment.body
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @comments

app/views/events/user_likes.html.haml
.page-header
  %h1.text-center
    = @user.email
    = t('.likes')
%table.table
  %thead
    %th= t('.date_time')
    %th= t('.picture')
  %tbody
    - @likes.each do |like|
      %tr
        %td= like.created_at
        %td= like.picture_id
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @likes

app/views/events/user_navigation.html.haml
.page-header
  %h1.text-center
    = @user.email
    = t('.navigation')
%table.table
  %thead
    %th= t('.date_time')
    %th= t('.url')
  %tbody
    - @navigations.each do |navigation|
      %tr
        %td= navigation.created_at
        %td= navigation.url
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @navigations

app/views/events/user_sign_in.html.haml
.page-header
  %h1.text-center
    = @user.email
    = t('.sign_ins')
%table.table
  %thead
    %th= t('.date_time')
    %th= t('.url')
  %tbody
    - @actions.each do |action|
      %tr
        %td= action.created_at
        %td= action.url
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @actions

app/views/events/user_sign_out.html.haml
.page-header
  %h1.text-center
    = @user.email
    = t('.sign_outs')
%table.table
  %thead
    %th= t('.date_time')
    %th= t('.url')
  %tbody
    - @actions.each do |action|
      %tr
        %td= action.created_at
        %td= action.url
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @actions