config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'static_pages#index'
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, param: :category_name, only: [:index, :show] do
    get ':id', to: 'pictures#show', as: 'picture'
  end
  resources :pictures, only: [:index]
  resources :comments, only: [:index]
  post '/:picture_id/comments', to: 'comments#create', as: 'create_comment'
  resources :likes, path: '/:picture_id/likes', only: [:create, :destroy]
  resources :events, only: [:index]
  resources :subscriptions, path: '/:category_id/subscriptions', only: [:create, :destroy]

  resources :chat_rooms, only: [:new, :create, :index, :show]

  get 'events/:id/comments', to: 'events#user_comments', as: 'user_comments'
  get 'events/:id/likes', to: 'events#user_likes', as: 'user_likes'
  get 'events/:id/navigation', to: 'events#user_navigation', as: 'user_navigation'
  get 'events/:id/user_sign_in', to: 'events#user_sign_in', as: 'user_sign_in'
  get 'events/:id/user_sign_out', to: 'events#user_sign_out', as: 'user_sign_out'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server.new, :at => '/resque'
  mount ActionCable.server, :at => '/cable'
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :category, presence: true

  after_save :send_email_to_subscribers

  def send_email_to_subscribers
    if self.category
      subscribers = self.category.users
      picture = self
      subscribers.each do |subscriber|
        PicturesMailer.new_picture_email(subscriber, picture).deliver_later
      end
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
    @pictures = Picture.all.order(likes_count: :desc).page(params[:page]).per(8)
  end

  def show
    @category = Category.find_by(category_name: params[:category_category_name])
    @picture = Picture.find_by(id: params[:id], category_id: @category.id)
    @like = Like.find_by(picture_id: params[:id], user_id: current_user.id) if user_signed_in?
    @comments = @picture.comments.order(created_at: :desc).page(params[:page]).per(5)
    @comments_counter = @picture.comments.count
  end
end

app/views/pictures/_dislike_it.html.haml
= form_for :like, url: like_path(@picture, @like), method: 'delete', remote: true do |f|
  %input{type: 'image', src: "#{asset_path 'like.png'}", alt: 'Submit', width: '48', height: '48'}
  %span
    = @picture.likes.count
    = t('.like', count: @picture.likes.count)

app/views/pictures/_form.html.haml
= form_for :comment, url: create_comment_path(@picture), remote: true do |f|
  .form-group
    = f.text_area :body, class: 'form-control'
    %br
    = f.submit t('.add_comment'), class: 'btn btn-primary'

app/views/pictures/_like_it.html.haml
= form_for :like, url: likes_path(@picture), remote: true do |f|
  %input{type: 'image', src: "#{asset_path 'like_empty.png'}", alt: 'Submit', width: '48', height: '48'}
  %span
    = @picture.likes.count
    = t('.like', count: @picture.likes.count)

app/views/pictures/index.html.haml
.page-header
  %h1.text-center= t('.pictures')
.row
  - @pictures.each do |picture|
    %div.col-xs-6.col-sm-4.col-md-3
      %a.thumbnail{href: "#{category_picture_url(picture.category.category_name, picture)}"}
        .image-holder.center-block
          %img.cover{src: "#{picture.image.thumb.url}"}
          .text-center.caption.image-header
            = image_tag 'heart.png'
            %span.small
              = picture.likes_count || 0
              = t('.like', count: (picture.likes_count || 0))
%nav{'aria-label' => 'Page navigation', class: 'text-center'}
  = paginate @pictures

app/views/pictures/show.html.haml
%a.thumbnail{href: '#', 'data-toggle' => 'modal', 'data-target' => "#myModal"}
  .image-holder-show.center-block
    %img.img-responsive.center-block{src: "#{@picture.image.url}"}

.modal.fade.bs-example-modal-lg{id: "myModal", tabindex: "-1", role: "dialog", 'aria-labelledby' => "myModalLabel"}
  .modal-dialog.modal-lg{role: "document"}
    .modal-content  
      .modal-body
        %button.close{type: "button", 'data-dismiss' => "modal", 'aria-label' => "Close"}
          &times;
        %img.img-responsive.center-block{src: "#{@picture.image.url}"}
      .modal-footer
        %button.btn.btn-default{type: "button", 'data-dismiss' => "modal"}
          Close

- if user_signed_in?
  #like-form
    = render @like.nil? ? 'like_it' : 'dislike_it'
%br
%h4#comments-counter
  = @comments_counter
  = t('.comment', count: @comments_counter)
- if user_signed_in?
  #comment-form
    = render 'form'
.comments-list
  = render @comments
%nav{'aria-label' => 'Page navigation', class: 'text-center pagination-holder'}
  = paginate @comments