config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'static_pages#index'
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, param: :category_name, only: [:index, :show] do
    get ':id', to: 'pictures#show', as: 'picture'
  end
  resources :pictures, only: [:index]
  resources :comments, only: [:index]
  post '/:picture_id/comments', to: 'comments#create', as: 'create_comment'
  resources :likes, path: '/:picture_id/likes', only: [:create, :destroy]
  resources :events, only: [:index]
  resources :subscriptions, path: '/:category_id/subscriptions', only: [:create, :destroy]

  resources :chat_rooms, only: [:new, :create, :index, :show]

  get 'events/:id/comments', to: 'events#user_comments', as: 'user_comments'
  get 'events/:id/likes', to: 'events#user_likes', as: 'user_likes'
  get 'events/:id/navigation', to: 'events#user_navigation', as: 'user_navigation'
  get 'events/:id/user_sign_in', to: 'events#user_sign_in', as: 'user_sign_in'
  get 'events/:id/user_sign_out', to: 'events#user_sign_out', as: 'user_sign_out'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server.new, :at => '/resque'
  mount ActionCable.server, :at => '/cable'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pictures, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions

  validates :category_name, presence: true,
                            length: { minimum: 2, maximum: 20 },
                            uniqueness: { case_sensitive: false }

  before_save { self.category_name = category_name.downcase }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(category_name: params[:category_name])
    @pictures = @category.pictures.page(params[:page]).per(8)
    @subscription = Subscription.find_by(category_id: @category.id, user_id: current_user.id) if user_signed_in?
  end
end

app/views/categories/_subscribe.html.haml
= form_for :subscription, url: subscriptions_path(@category), remote: true do |f|
  .form-group
    %br
    = f.submit t('.subscribe'), class: 'btn btn-primary'

app/views/categories/_unsubscribe.html.haml
= form_for :subscription, url: subscription_path(@category, @subscription), method: 'delete', remote: true do |f|
  .form-group
    %br
    = f.submit t('.unsubscribe'), class: 'btn btn-default'

app/views/categories/index.html.haml
.page-header
  %h1.text-center= t('.categories')
.row
  - @categories.each do |category|
    %div.col-sm-6.col-md-4.col-lg-3
      %a.thumbnail.text-center{href: "#{category_url(category.category_name)}"}
        .image-category-holder.center-block
          = image_tag category.pictures.first.image.url, class: 'cover' if category.pictures.any?
        %h4= category.category_name.upcase

app/views/categories/show.html.haml
.page-header
  %h1.text-center= @category.category_name.capitalize
  - if user_signed_in?
    #subscribe-form.text-center
      = render @subscription.nil? ? 'subscribe' : 'unsubscribe'
- if @pictures
  .row
    - @pictures.each do |picture|
      %div.col-xs-6.col-sm-4.col-md-3
        %a.thumbnail{href: "#{category_picture_url(picture.category.category_name, picture)}"}
          .image-holder.center-block
            %img.cover{src: "#{picture.image.thumb.url}"}
            .text-center.caption.image-header
              = image_tag 'heart.png'
              %span.small
                = picture.likes_count || 0
                = t('.like', count: (picture.likes_count || 0))
  %nav{'aria-label' => 'Page navigation', class: 'text-center'}
    = paginate @pictures
  