config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'static_pages#index'
  devise_for :users, controllers: { sessions: 'users/sessions',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :categories, param: :category_name, only: [:index, :show] do
    get ':id', to: 'pictures#show', as: 'picture'
  end
  resources :pictures, only: [:index]
  resources :comments, only: [:index]
  post '/:picture_id/comments', to: 'comments#create', as: 'create_comment'
  resources :likes, path: '/:picture_id/likes', only: [:create, :destroy]
  resources :events, only: [:index]
  resources :subscriptions, path: '/:category_id/subscriptions', only: [:create, :destroy]

  resources :chat_rooms, only: [:new, :create, :index, :show]

  get 'events/:id/comments', to: 'events#user_comments', as: 'user_comments'
  get 'events/:id/likes', to: 'events#user_likes', as: 'user_likes'
  get 'events/:id/navigation', to: 'events#user_navigation', as: 'user_navigation'
  get 'events/:id/user_sign_in', to: 'events#user_sign_in', as: 'user_sign_in'
  get 'events/:id/user_sign_out', to: 'events#user_sign_out', as: 'user_sign_out'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Resque::Server.new, :at => '/resque'
  mount ActionCable.server, :at => '/cable'
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    %p.text-center
      = image_tag('facebook.png', class: 'social-img')
      = image_tag('pinterest.png', class: 'social-img')
      = image_tag('instagram.png', class: 'social-img')
    %p.text-center
      %small &copy; 2017 by Volodymyr Stepanov

app/views/layouts/_header.html.haml
%header.header
  %nav.navbar.navbar-inverse.text-uppercase
    .container
      .navbar-header
        %button{type: 'button', class: 'navbar-toggle collapsed', data: {toggle: 'collapse', target: '#bs-example-navbar-collapse-1'}, 'aria-expanded' => 'false'}
          %span.sr-only Main menu
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to t('.gallery'), root_path, class: 'navbar-brand'
      %div{class: 'collapse navbar-collapse', id: 'bs-example-navbar-collapse-1'}
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to t('.categories'), categories_path
          %li
            = link_to t('.pictures'), pictures_path
          - if user_signed_in?
            %li
              = link_to t('.chat_rooms'), chat_rooms_path
            %li.dropdown
              %a{href: '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', role: 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'}
                = t('.tracking')
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to t('.comments'), comments_path
                %li
                  = link_to t('.events'), events_path
            %li.dropdown
              %a{href: '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', role: 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false'}
                = current_user.email
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to t('.profile'), edit_user_registration_path
                %li
                  = link_to t('.sign_out'), destroy_user_session_path, method: 'delete'
          - else
            %li
              = link_to t('.sign_in'), new_user_session_path
            %li
              = link_to t('.sign_up'), new_user_registration_path
          %li
            %p.navbar-text
              = link_to t('.en'), "#{url_for(locale: :en)}", class: 'navbar-link'
              |
              = link_to t('.ru'), "#{url_for(locale: :ru)}", class: 'navbar-link'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= t('gallery')
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    = render 'layouts/header'
    %main
      .container
        - flash.each do |key, value|
          - alert_class = ( key == 'notice' || key == 'success' ) ? 'success' : 'danger'
          = content_tag(:div, value, class: "alert alert-#{alert_class}")
      
        = yield

    =render 'layouts/footer'